sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: qyys@cle
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tGwGS9AR9p8NzqpKzbf
    access-key-secret: TcdIPKOh5Cv9CllKEqe7bXdCc8bN1M
    bucket-name: my-ai-test-images
  redis:
    host: localhost
    port: 6379

    database: 10
  wechat:
    appid: wx15235f143e26de69
    secret: eb078e9c7bddf91b1fdc838b4acb08ec
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://58869fb.r2.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess
