# 应用服务 WEB 访问端口
server:
  port: 7090
  #session过期时间 60M 一个小时
  servlet:
    session:
      timeout: 0
 #数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yunpan
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#发送邮件配置相关
# 配置邮件服务器的地址 smtp.qq.com
  mail:
    host: smtp.qq.com
# 配置邮件服务器的端口（465或587）
    port: 465
# 配置用户的账号
    username: dhx12.12@qq.com
# 配置用户的密码
    password: xtlujkbyklxodief
# 配置默认编码
    default-encoding: UTF-8
# SSL 连接配置
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
# 开启 debug，这样方便开发者查看邮件发送日志
        debug: true
#邮件配置结束
#Spring redis配置
# Redis数据库索引（默认为0）

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10          # 连接池中的最大空闲连接
        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0           # 连接池中的最小空闲连接
        timeout: 5000
  servlet:
    multipart:
      max-request-size: 10MB
#超级管理员id
admin:
  emails:
    1973284650@qq.com
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

